/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelera_exportation.View;

import Model.Crear_UsuarioDTO;
import java.util.Date;
import panelera_exportation.Controller.Crear_UsuarioController;
import Funciones.Validacion;
import java.beans.Encoder;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Funciones.Endcoder;

/**
 *
 * @author Cris
 */
public class Create_User extends javax.swing.JFrame {

    private String _full_name, _email, _phone_number, _address, _user_name, _password;
    private int Phone_Number;

    // Variables for responsive scaling
    private int originalWidth = 550;
    private int originalHeight = 730;
    private java.util.HashMap<java.awt.Component, java.awt.Rectangle> originalBounds = new java.util.HashMap<>();
    private java.util.HashMap<java.awt.Component, java.awt.Font> originalFonts = new java.util.HashMap<>();

    /**
     * Creates new form Create_User
     */
    public Create_User() {
        initComponents();
        this.setLocationRelativeTo(null);
        setupResponsiveScaling();

    }

    private void setupResponsiveScaling() {
        // Store original bounds and fonts of all components
        for (java.awt.Component comp : getContentPane().getComponents()) {
            originalBounds.put(comp, comp.getBounds());
            if (comp.getFont() != null) {
                originalFonts.put(comp, comp.getFont());
            }
        }

        // Add component listener to handle resizing
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                scaleComponents();
            }
        });
    }

    private void scaleComponents() {
        int currentWidth = getWidth();
        int currentHeight = getHeight();

        double scaleX = (double) currentWidth / originalWidth;
        double scaleY = (double) currentHeight / originalHeight;

        for (java.awt.Component comp : getContentPane().getComponents()) {
            java.awt.Rectangle originalRect = originalBounds.get(comp);
            if (originalRect != null) {
                int newX = (int) (originalRect.x * scaleX);
                int newY = (int) (originalRect.y * scaleY);
                int newWidth = (int) (originalRect.width * scaleX);
                int newHeight = (int) (originalRect.height * scaleY);

                comp.setBounds(newX, newY, newWidth, newHeight);

                // Scale font size for labels and buttons using ORIGINAL font
                if (comp instanceof javax.swing.JLabel || comp instanceof javax.swing.JButton ||
                    comp instanceof javax.swing.JTextField) {
                    java.awt.Font originalFont = originalFonts.get(comp);
                    if (originalFont != null) {
                        float newSize = (float) (originalFont.getSize() * Math.min(scaleX, scaleY));
                        comp.setFont(originalFont.deriveFont(newSize));
                    }
                }
            }
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFull_Name = new javax.swing.JLabel();
        txtFull_Name = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone_Number = new javax.swing.JLabel();
        lblUser_Name = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone_Number = new javax.swing.JTextField();
        txtUser_Name = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCreat_User = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        lblFecha_Nacimiento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblFull_Name.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblFull_Name.setForeground(new java.awt.Color(255, 255, 255));
        lblFull_Name.setText("Full Name");
        getContentPane().add(lblFull_Name);
        lblFull_Name.setBounds(33, 90, 103, 32);

        txtFull_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFull_NameActionPerformed(evt);
            }
        });
        getContentPane().add(txtFull_Name);
        txtFull_Name.setBounds(200, 91, 218, 32);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(33, 159, 103, 32);

        lblPhone_Number.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblPhone_Number.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone_Number.setText("Phone Number");
        getContentPane().add(lblPhone_Number);
        lblPhone_Number.setBounds(33, 254, 125, 32);

        lblUser_Name.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblUser_Name.setText("User Name");
        getContentPane().add(lblUser_Name);
        lblUser_Name.setBounds(33, 449, 103, 32);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(200, 160, 218, 32);
        getContentPane().add(txtPhone_Number);
        txtPhone_Number.setBounds(200, 254, 218, 32);
        getContentPane().add(txtUser_Name);
        txtUser_Name.setBounds(200, 450, 218, 32);

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(33, 522, 103, 32);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(200, 523, 218, 32);

        btnCreat_User.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btnCreat_User.setText("Create User");
        btnCreat_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreat_UserActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreat_User);
        btnCreat_User.setBounds(231, 644, 108, 24);
        getContentPane().add(txtAddress);
        txtAddress.setBounds(200, 331, 218, 61);

        lblAddress.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Address");
        getContentPane().add(lblAddress);
        lblAddress.setBounds(33, 345, 125, 32);

        lblFecha_Nacimiento.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblFecha_Nacimiento.setText("Fecha Nacimiento");
        getContentPane().add(lblFecha_Nacimiento);
        lblFecha_Nacimiento.setBounds(33, 586, 134, 23);

        jDateFecha_naciemiento = new com.toedter.calendar.JDateChooser();
        getContentPane().add(jDateFecha_naciemiento);
        jDateFecha_naciemiento.setBounds(175, 586, 200, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exportation Image 4.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(2, 7, 530, 690);

        setSize(550, 730);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFull_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFull_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFull_NameActionPerformed

    private void btnCreat_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreat_UserActionPerformed
        // TODO add your handling code here:
        Date Fecha_nacimiento = jDateFecha_naciemiento.getDate();
        Crear_UsuarioDTO registrarcreate_User = new Crear_UsuarioDTO();
        Crear_UsuarioController nuevaCreate_User = new Crear_UsuarioController();
        Endcoder encoder = new Endcoder();
        Validacion validacion = new Validacion();

        if (!txtFull_Name.getText().trim().equals("") && !txtEmail.getText().trim().equals("") && !txtPhone_Number.getText().trim().equals("") && !txtAddress.getText().trim().equals("") && !txtUser_Name.getText().trim().equals("") && !txtPassword.getText().trim().equals("")) {
        }

        if (!(validacion.ValidarEmail(txtEmail.getText().trim()))) {
            JOptionPane.showMessageDialog(rootPane, "El correo no es valido.");
            return;
        }

        if (txtPhone_Number.getText().length() == 10 && txtPhone_Number.getText().matches("[0-9]*")) {

        }

        _full_name = txtFull_Name.getText().trim();

        _email = txtEmail.getText().trim();

        _address = txtAddress.getText().trim();

        _user_name = txtUser_Name.getText().trim();

        _password = txtPassword.getText().trim();

        _phone_number = txtPhone_Number.getText().trim();

        registrarcreate_User.setFull_Name(_full_name);

        registrarcreate_User.setPhone_Number(Phone_Number);

        registrarcreate_User.setAddress(_address);
        registrarcreate_User.setUser_Name(_user_name);

        registrarcreate_User.setFecha_nacimiento(Fecha_nacimiento);

        validacion.ValidarEmail(_email);
        registrarcreate_User.setEmail(_email);

        try {
            encoder.encrypt(_password);
            registrarcreate_User.setPassword(encoder.getClave_encrypt());

        } catch (Exception ex) {
            Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            nuevaCreate_User.create_User(registrarcreate_User);

        } catch (SQLException ex) {
            Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
        }
        Singin_panelera singin = new Singin_panelera();
        singin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCreat_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreat_User;
    private com.toedter.calendar.JDateChooser jDateFecha_naciemiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha_Nacimiento;
    private javax.swing.JLabel lblFull_Name;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone_Number;
    private javax.swing.JLabel lblUser_Name;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFull_Name;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone_Number;
    private javax.swing.JTextField txtUser_Name;
    // End of variables declaration//GEN-END:variables
}
