/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelera_exportation.View;

import Model.Crear_UsuarioDTO;
import java.util.Date;
import panelera_exportation.Controller.Crear_UsuarioController;
import Funciones.Validacion;
import java.beans.Encoder;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Funciones.Endcoder;

/**
 *
 * @author Cris
 */
public class Create_User extends javax.swing.JFrame {

    private String _full_name, _email, _phone_number, _address, _user_name, _password;
    private int Phone_Number;

    /**
     * Creates new form Create_User
     */
    public Create_User() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFull_Name = new javax.swing.JLabel();
        txtFull_Name = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPhone_Number = new javax.swing.JLabel();
        lblUser_Name = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone_Number = new javax.swing.JTextField();
        txtUser_Name = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnCreat_User = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jDateFecha_naciemiento = new com.toedter.calendar.JDateChooser();
        lblFecha_Nacimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFull_Name.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblFull_Name.setText("Full Name");

        txtFull_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFull_NameActionPerformed(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblEmail.setText("Email");

        lblPhone_Number.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblPhone_Number.setText("Phone Number");

        lblUser_Name.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblUser_Name.setText("User Name");

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblPassword.setText("Password");

        btnCreat_User.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btnCreat_User.setText("Create User");
        btnCreat_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreat_UserActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblAddress.setText("Address");

        lblFecha_Nacimiento.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lblFecha_Nacimiento.setText("Fecha Nacimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha_Nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFull_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(txtPhone_Number))
                        .addComponent(txtUser_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFull_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCreat_User)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDateFecha_naciemiento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFull_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFull_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFecha_Nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateFecha_naciemiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 35, Short.MAX_VALUE)
                .addComponent(btnCreat_User)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFull_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFull_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFull_NameActionPerformed

    private void btnCreat_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreat_UserActionPerformed
        // TODO add your handling code here:
        Date Fecha_nacimiento = jDateFecha_naciemiento.getDate();
        Crear_UsuarioDTO registrarcreate_User = new Crear_UsuarioDTO();
        Crear_UsuarioController nuevaCreate_User = new Crear_UsuarioController();
        Endcoder encoder = new Endcoder();
        Validacion validacion = new Validacion();

        if (!txtFull_Name.getText().trim().equals("") && !txtEmail.getText().trim().equals("") && !txtPhone_Number.getText().trim().equals("") && !txtAddress.getText().trim().equals("") && !txtUser_Name.getText().trim().equals("") && !txtPassword.getText().trim().equals("")) {
        }

        if (!(validacion.ValidarEmail(txtEmail.getText().trim()))) {
            JOptionPane.showMessageDialog(rootPane, "El correo no es valido.");
            return;
        }

        if (txtPhone_Number.getText().length() == 10 && txtPhone_Number.getText().matches("[0-9]*")) {

        }

        _full_name = txtFull_Name.getText().trim();

        _email = txtEmail.getText().trim();

        _address = txtAddress.getText().trim();

        _user_name = txtUser_Name.getText().trim();

        _password = txtPassword.getText().trim();

        _phone_number = txtPhone_Number.getText().trim();

        registrarcreate_User.setFull_Name(_full_name);

        registrarcreate_User.setPhone_Number(Phone_Number);

        registrarcreate_User.setAddress(_address);
        registrarcreate_User.setUser_Name(_user_name);

        registrarcreate_User.setFecha_nacimiento(Fecha_nacimiento);

        validacion.ValidarEmail(_email);
        registrarcreate_User.setEmail(_email);

        try {
            encoder.encrypt(_password);
            registrarcreate_User.setPassword(encoder.getClave_encrypt());

        } catch (Exception ex) {
            Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            nuevaCreate_User.create_User(registrarcreate_User);

        } catch (SQLException ex) {
            Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
        }
        Singin_panelera singin = new Singin_panelera();
        singin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCreat_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreat_User;
    private com.toedter.calendar.JDateChooser jDateFecha_naciemiento;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFecha_Nacimiento;
    private javax.swing.JLabel lblFull_Name;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone_Number;
    private javax.swing.JLabel lblUser_Name;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFull_Name;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone_Number;
    private javax.swing.JTextField txtUser_Name;
    // End of variables declaration//GEN-END:variables
}
