/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelera_exportation.View;

import javax.swing.table.DefaultTableModel;
import Model.Create_OrderDTO;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import panelera_exportation.Controller.Create_OrderController;

/**
 *
 * @author Cris
 */
public class Order_Spreadsheet extends javax.swing.JFrame {

    private String destination;
    private double precio;
    private Date date;
    private String full_name;
    private String product_type;
    private String amount_order;
    private String currency;
    private String shipping_type;
    private String total;

    /**
     * Creates new form Order_Spreadsheet
     */
    public Order_Spreadsheet() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);

        traerDatosTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        lblEmploye_ID = new javax.swing.JLabel();
        txtEmploye_ID = new javax.swing.JTextField();
        lblEmploye_Full_Name = new javax.swing.JLabel();
        txtFull_Name = new javax.swing.JTextField();
        lblDestination = new javax.swing.JLabel();
        lblShipping_Type = new javax.swing.JLabel();
        bxShipping_type = new javax.swing.JComboBox<>();
        lblProduct_Type = new javax.swing.JLabel();
        bxProducto_Type = new javax.swing.JComboBox<>();
        lblAmount = new javax.swing.JLabel();
        txtAmount_Order = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblCurrency = new javax.swing.JLabel();
        bxCurrency = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSearch = new javax.swing.JTextPane();
        txtDestination = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblImage_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(1200, 1200));
        setMaximumSize(new java.awt.Dimension(1200, 1200));
        setMinimumSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(null);

        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(740, 20, 73, 33);

        btnEdit.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(600, 20, 72, 33);

        jScrollPane2.setViewportView(tbOrder);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(373, 62, 715, 384);

        lblEmploye_ID.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmploye_ID.setForeground(new java.awt.Color(255, 255, 255));
        lblEmploye_ID.setText("Employe ID");
        getContentPane().add(lblEmploye_ID);
        lblEmploye_ID.setBounds(6, 50, 99, 32);
        getContentPane().add(txtEmploye_ID);
        txtEmploye_ID.setBounds(111, 51, 128, 32);

        lblEmploye_Full_Name.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblEmploye_Full_Name.setForeground(new java.awt.Color(255, 255, 255));
        lblEmploye_Full_Name.setText("Full Name");
        getContentPane().add(lblEmploye_Full_Name);
        lblEmploye_Full_Name.setBounds(6, 115, 99, 32);
        getContentPane().add(txtFull_Name);
        txtFull_Name.setBounds(111, 116, 157, 32);

        lblDestination.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(255, 255, 255));
        lblDestination.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logistics.png"))); // NOI18N
        lblDestination.setText("Destination");
        getContentPane().add(lblDestination);
        lblDestination.setBounds(6, 166, 154, 64);

        lblShipping_Type.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblShipping_Type.setForeground(new java.awt.Color(255, 255, 255));
        lblShipping_Type.setText("Shipping Type");
        getContentPane().add(lblShipping_Type);
        lblShipping_Type.setBounds(16, 289, 110, 18);

        bxShipping_type.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bxShipping_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baot", "Plane" }));
        getContentPane().add(bxShipping_type);
        bxShipping_type.setBounds(16, 325, 90, 24);

        lblProduct_Type.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblProduct_Type.setForeground(new java.awt.Color(255, 255, 255));
        lblProduct_Type.setText("Product Type");
        getContentPane().add(lblProduct_Type);
        lblProduct_Type.setBounds(16, 367, 90, 27);

        bxProducto_Type.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bxProducto_Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Panela", "Sugar", "wine", "Ethanol", "Syrup" }));
        bxProducto_Type.setName(""); // NOI18N
        getContentPane().add(bxProducto_Type);
        bxProducto_Type.setBounds(16, 400, 90, 24);

        lblAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblAmount.setText("Amount Order");
        getContentPane().add(lblAmount);
        lblAmount.setBounds(565, 450, 104, 27);
        getContentPane().add(txtAmount_Order);
        txtAmount_Order.setBounds(565, 485, 104, 23);

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setText("Total");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(749, 450, 64, 27);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(728, 485, 85, 23);

        lblCurrency.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCurrency.setText("Currency");
        getContentPane().add(lblCurrency);
        lblCurrency.setBounds(872, 449, 89, 28);

        bxCurrency.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        bxCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dollar", "Euro" }));
        getContentPane().add(bxCurrency);
        bxCurrency.setBounds(872, 484, 89, 24);

        btnSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(64, 480, 76, 33);

        jScrollPane1.setViewportView(txtSearch);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(34, 531, 144, 30);

        txtDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinationActionPerformed(evt);
            }
        });
        getContentPane().add(txtDestination);
        txtDestination.setBounds(16, 236, 132, 41);

        btnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(890, 20, 72, 33);

        lblImage_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Exportation Image 4.png"))); // NOI18N
        getContentPane().add(lblImage_4);
        lblImage_4.setBounds(2, 7, 1140, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        String employe_ID = txtEmploye_ID.getText();
        if (employe_ID.isEmpty() || employe_ID.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Data Need to be enter", "EMploye ID Emtpty", JOptionPane.ERROR_MESSAGE);
        } else {
            Create_OrderController deleteorder = new Create_OrderController();
            deleteorder.deleteOrder(Integer.parseInt(employe_ID));
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        Create_OrderController editOrder = new Create_OrderController();
        Create_OrderDTO infoActualizar = new Create_OrderDTO();

        //Editar registros
        String employe_ID = txtEmploye_ID.getText();
        if (employe_ID.isEmpty() || employe_ID.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Data Need to be enter", "EMploye ID Emtpty", JOptionPane.ERROR_MESSAGE);
        }

        full_name = txtFull_Name.getText();
        destination = txtDestination.getText();

        switch (bxProducto_Type.getSelectedIndex()) {
            case 0:
                product_type = "Panela";
                break;
            case 1:
                product_type = "Sugar";
                break;
            case 2:
                product_type = "Wine";
                break;
            case 3:
                product_type = "Ethanol";
                break;
            case 4:
                product_type = "Syrup";
                break;
            default:
                System.out.println("No hay producto seleccionado");
        }

        switch (bxCurrency.getSelectedIndex()) {
            case 0 -> {
                currency = "Dollar";
                precio = 4500;
            }
            case 1 -> {
                currency = "Euro";
                precio = 5500;
            }
            default ->
                currency = "ERror";
        }

        shipping_type = switch (bxShipping_type.getSelectedIndex()) {
            case 0 ->
                "Boat";
            case 1 ->
                "Plane";
            default ->
                "Car";
        };

        amount_order = txtAmount_Order.getText();
        total = String.valueOf(Integer.parseInt(amount_order) * precio);
        txtTotal.setText(total);

        destination = txtDestination.getText();
        
        infoActualizar.setDestination(destination);
        infoActualizar.setCurrency(currency);
        infoActualizar.setShipping_type(shipping_type);
        infoActualizar.setProduct_type(product_type);
        infoActualizar.setAmount_order(amount_order);
        infoActualizar.setTota(total);
        infoActualizar.setFull_name(full_name);
        
        editOrder.actualizarData(infoActualizar, Integer.parseInt(employe_ID));


    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String employe_ID = txtSearch.getText();
        if (employe_ID.isEmpty() || employe_ID.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Data Need to be enter", "EMploye ID Emtpty", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Create_OrderController consultEmploye_ID = new Create_OrderController();
        Create_OrderDTO search = null;
        try {
            search = consultEmploye_ID.consultemploye_ID(Integer.parseInt(employe_ID));
        } catch (SQLException ex) {
            Logger.getLogger(Order_Spreadsheet.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (search != null) {
            txtAmount_Order.setText(search.getAmount_order());
            txtDestination.setText(search.getDestination());
            txtFull_Name.setText(search.getFull_name());
            txtTotal.setText(search.getTota());

            switch (search.getShipping_type()) {
                case "Plane":
                    bxShipping_type.setSelectedIndex(0);
                    break;
                case "Boat":
                    bxShipping_type.setSelectedIndex(1);
                    break;
                default:
                    throw new AssertionError();

            }
            switch (search.getProduct_type()) {
                case "Panela" ->
                    bxProducto_Type.setSelectedIndex(0);
                case "Sugar" ->
                    bxProducto_Type.setSelectedIndex(1);

                case "Wine" ->
                    bxProducto_Type.setSelectedIndex(2);
                case "Ethanol" ->
                    bxProducto_Type.setSelectedIndex(3);

                case "Syrup" ->
                    bxProducto_Type.setSelectedIndex(4);
                default ->
                    throw new AssertionError();
            }
            switch (search.getCurrency()) {
                case "Dollar" ->
                    bxCurrency.setSelectedIndex(0);
                case "Euro" ->
                    bxCurrency.setSelectedIndex(1);
                default ->
                    throw new AssertionError();

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hemos encontrado datos.");
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Create_Order create_order = new Create_Order();
        create_order.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAddActionPerformed

    void traerDatosTabla() throws SQLException {
        DefaultTableModel model = new DefaultTableModel();

        Create_OrderController create_order = new Create_OrderController();
        List<Create_OrderDTO> listarOrdenes = create_order.listadoTotal();
        String[] titulos = {"employe_ID", "full_name", "produc_type", "amount_order", "destination", "date", "currency", "Total", "shipping_type", "total"};
        model = new DefaultTableModel(null, titulos);
        tbOrder.setModel(model);

        for (Create_OrderDTO ordenes : listarOrdenes) {
            Object[] filas = new Object[9];
            filas[0] = ordenes.getEmploye_ID();
            filas[1] = ordenes.getFull_name();
            filas[2] = ordenes.getProduct_type();
            filas[3] = ordenes.getAmount_order();
            filas[4] = ordenes.getDestination();
            filas[5] = ordenes.getFechaEnvio();
            filas[6] = ordenes.getCurrency();
            filas[7] = ordenes.getTota();
            filas[8] = ordenes.getShipping_type();
            model.addRow(filas);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Spreadsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Spreadsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Spreadsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Spreadsheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Order_Spreadsheet().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Order_Spreadsheet.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> bxCurrency;
    private javax.swing.JComboBox<String> bxProducto_Type;
    private javax.swing.JComboBox<String> bxShipping_type;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCurrency;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblEmploye_Full_Name;
    private javax.swing.JLabel lblEmploye_ID;
    private javax.swing.JLabel lblImage_4;
    private javax.swing.JLabel lblProduct_Type;
    private javax.swing.JLabel lblShipping_Type;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTextField txtAmount_Order;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtEmploye_ID;
    private javax.swing.JTextField txtFull_Name;
    private javax.swing.JTextPane txtSearch;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
