/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelera_exportation.View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import panelera_exportation.Controller.LoginController;

/**
 *
 * @author Cris
 */
public class Singin_panelera extends javax.swing.JFrame {

    // Variables for responsive scaling
    private int originalWidth = 940;
    private int originalHeight = 420;
    private java.util.HashMap<java.awt.Component, java.awt.Rectangle> originalBounds = new java.util.HashMap<>();
    private java.util.HashMap<java.awt.Component, java.awt.Font> originalFonts = new java.util.HashMap<>();

    /**
     * Creates new form
     */
    public Singin_panelera() {
        initComponents();
        this.setLocationRelativeTo(null);
        setupResponsiveScaling();
    }

    private void setupResponsiveScaling() {
        // Store original bounds and fonts of all components
        for (java.awt.Component comp : getContentPane().getComponents()) {
            originalBounds.put(comp, comp.getBounds());
            if (comp.getFont() != null) {
                originalFonts.put(comp, comp.getFont());
            }
        }

        // Add component listener to handle resizing
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                scaleComponents();
            }
        });
    }

    private void scaleComponents() {
        int currentWidth = getWidth();
        int currentHeight = getHeight();

        double scaleX = (double) currentWidth / originalWidth;
        double scaleY = (double) currentHeight / originalHeight;

        for (java.awt.Component comp : getContentPane().getComponents()) {
            java.awt.Rectangle originalRect = originalBounds.get(comp);
            if (originalRect != null) {
                int newX = (int) (originalRect.x * scaleX);
                int newY = (int) (originalRect.y * scaleY);
                int newWidth = (int) (originalRect.width * scaleX);
                int newHeight = (int) (originalRect.height * scaleY);

                comp.setBounds(newX, newY, newWidth, newHeight);

                // Scale font size for labels and buttons using ORIGINAL font
                if (comp instanceof javax.swing.JLabel || comp instanceof javax.swing.JButton ||
                    comp instanceof javax.swing.JTextField || comp instanceof javax.swing.JPasswordField) {
                    java.awt.Font originalFont = originalFonts.get(comp);
                    if (originalFont != null) {
                        float newSize = (float) (originalFont.getSize() * Math.min(scaleX, scaleY));
                        comp.setFont(originalFont.deriveFont(newSize));
                    }
                }
            }
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbluser_name = new javax.swing.JLabel();
        btnLoging = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        btnCreate_user = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbluser_name.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbluser_name.setForeground(new java.awt.Color(255, 255, 255));
        lbluser_name.setText("USERNAME");
        getContentPane().add(lbluser_name);
        lbluser_name.setBounds(195, 75, 158, 40);

        btnLoging.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLoging.setText("LOGIN");
        btnLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogingActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoging);
        btnLoging.setBounds(464, 250, 138, 37);

        txtusername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        getContentPane().add(txtusername);
        txtusername.setBounds(365, 76, 320, 40);

        lblpassword.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword.setText("PASSWORD");
        getContentPane().add(lblpassword);
        lblpassword.setBounds(195, 191, 158, 40);

        fldPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        getContentPane().add(fldPassword);
        fldPassword.setBounds(365, 192, 320, 40);

        btnCreate_user.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnCreate_user.setText("Creat User");
        btnCreate_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate_userActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate_user);
        btnCreate_user.setBounds(464, 328, 138, 37);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Colombia-Major-Exports.jpeg"))); // NOI18N
        getContentPane().add(lblImage);
        lblImage.setBounds(12, 7, 910, 370);

        setSize(940, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogingActionPerformed
        LoginController logingController = new LoginController();
        String use = txtusername.getText();
        String pass = new String(fldPassword.getPassword());
        if (!(use.trim().equals("") || pass.trim().equals(""))) {
            try {
                if (logingController.validateusername(use, pass)) {

                    Create_Order Creord = new Create_Order();
                    Creord.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Username or PassWord is invalid");
                    cleanTextBox();
                }
            } catch (SQLException ex) {
                Logger.getLogger(Singin_panelera.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Singin_panelera.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes completar los campos requeridos", "Ingresa los valores", JOptionPane.ERROR_MESSAGE);
            cleanTextBox();
        }

    }//GEN-LAST:event_btnLogingActionPerformed

    private void btnCreate_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate_userActionPerformed
        Create_User CUsurio = new Create_User();
        CUsurio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreate_userActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Singin_panelera().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate_user;
    private javax.swing.JButton btnLoging;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluser_name;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    private void cleanTextBox() {
        this.txtusername.setText("");
        this.fldPassword.setText("");
    }
}
