/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panelera_exportation.View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import panelera_exportation.Controller.LoginController;

/**
 *
 * @author Cris
 */
public class Singin_panelera extends javax.swing.JFrame {

    /**
     * Creates new form sing_panelera
     */
    public Singin_panelera() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbluser_name = new javax.swing.JLabel();
        btnLoging = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        fldPassword = new javax.swing.JPasswordField();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 500));
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(null);

        lbluser_name.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbluser_name.setForeground(new java.awt.Color(255, 255, 255));
        lbluser_name.setText("USERNAME");
        getContentPane().add(lbluser_name);
        lbluser_name.setBounds(195, 75, 158, 40);

        btnLoging.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLoging.setText("LOGIN");
        btnLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogingActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoging);
        btnLoging.setBounds(379, 319, 138, 37);

        txtusername.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        getContentPane().add(txtusername);
        txtusername.setBounds(365, 76, 320, 40);

        lblpassword.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(255, 255, 255));
        lblpassword.setText("PASSWORD");
        getContentPane().add(lblpassword);
        lblpassword.setBounds(195, 191, 158, 40);

        fldPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        fldPassword.setText("jPasswordField1");
        getContentPane().add(fldPassword);
        fldPassword.setBounds(365, 192, 320, 40);

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Colombia-Major-Exports.jpeg"))); // NOI18N
        getContentPane().add(lblImage);
        lblImage.setBounds(12, 7, 900, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogingActionPerformed
       LoginController logingController = new LoginController();
        String  use= txtusername.getText();
        String  pass= new String(fldPassword.getPassword());
        try {
            if (logingController.validateusername(use,pass)){
                
                Create_Order Creord = new Create_Order();
                Creord.setVisible(true);
                this.dispose();
            }else
                JOptionPane.showMessageDialog(null,"Wrang Username or PassWord");
        } catch (SQLException ex) {
            Logger.getLogger(Singin_panelera.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnLogingActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Singin_panelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Singin_panelera().setVisible(true);
            }
        });
    
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoging;
    private javax.swing.JPasswordField fldPassword;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbluser_name;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
